-- CREATE A TABLE FROM 1 TO N=1000
WITH RECURSIVE TMP AS
(
    SELECT 1 AS NUM
    UNION ALL
    SELECT NUM+1 FROM TMP
    WHERE NUM < 1000
)
-- CONCAT ALL THE ROWS IN ONE STRING USING & AS SEPARATOR
SELECT GROUP_CONCAT(TMP3.NUM SEPARATOR '&') FROM 
(
    SELECT 
    TMP.NUM,
    -- COUNT HOW MANY TIMES YOU CAN DIVIDE A NUMBER
    SUM(IF(TMP.NUM % TMP2.NUM = 0 AND TMP.NUM > 3,1,0)) AS COUNTER
    FROM TMP
    JOIN TMP AS TMP2 ON TMP2.NUM < TMP.NUM
    GROUP BY TMP.NUM
    -- IF YOU CAN DIVIDE BETWEEN MORE THAN 1 NUMBER THEN
    -- YOU DO NOT HAVE A PRIME NUMBER
    HAVING COUNTER < 2
    ORDER BY TMP.NUM
) AS TMP3;
